pub mod error;
pub mod schema;
pub mod installation;
pub mod config;
pub mod ssh;
pub mod repository;
pub mod discovery;
pub mod dashboard;
pub mod groups;
pub mod status;
pub mod staging;
pub mod diff;
pub mod commit;
pub mod branch;
pub mod graph;
pub mod history;
pub mod remote;
pub mod conflict;
pub mod stash;
pub mod merge;
pub mod rebase;
pub mod cherrypick;
pub mod revert;
pub mod reset;
pub mod checkpoint;
pub mod ignore;
pub mod maintenance;
pub mod worktree;
pub mod submodule;
pub mod hooks;
pub mod internals;
pub mod plumbing;
pub mod hosting;
pub mod pull_requests;
pub mod enterprise;
pub mod audit;
pub mod cicd;

pub use error::GitEngineError;
pub use installation::{GitInstallation, detect_git, set_custom_git_path, parse_git_version, check_min_version};
pub use config::{GitConfigLevel, GitConfigEntry, read_system_config, read_global_config, set_global_config, read_local_config, set_local_config, set_remote_url, set_branch_upstream, backup_global_config};
pub use ssh::{SshKey, SshConfigHost, list_ssh_keys, read_ssh_config, generate_ed25519_key, compute_fingerprint};
pub use repository::{RepositoryHandle, CloneOptions, RepoHealth, open_repository, init_repository, clone_repository, check_repository_health};
pub use discovery::scan_directories;
pub use dashboard::{RepoCard, get_dashboard_cards, pin_repository, remove_repository};

pub use status::{FileStatus, StatusResult, DiffStats, SubmoduleSummary, get_repository_status};
pub use staging::{DiscardType, LineSelection, stage_file, unstage_file, stage_all, unstage_all, stage_patch, discard_changes};
pub use diff::{DiffLine, DiffHunk, DiffView, ImageDiff, get_file_diff, get_image_diff};
pub use commit::{CommitRequest, CommitListItem, ChangedFile, CommitDetail, HookResult, create_commit, get_commit_history, get_commit_details, execute_pre_commit_hook};
pub use branch::{BranchItem, BranchList, CheckoutStrategy, CheckoutResult, get_branches, create_branch, delete_branch, rename_branch, set_branch_upstream as branch_set_upstream, checkout_branch};
pub use graph::{GraphNode, GraphEdge, GraphView, get_commit_graph};
pub use history::{HistorySearchType, HistorySearchQuery, search_history};
pub use remote::{RemoteItem, ConnectionTestResult, FetchResult, PullStrategy, PullResult, PushResult, get_remotes, add_remote, remove_remote, edit_remote, prune_remote, test_remote_connection, fetch_remote, pull_branch, push_branch};
pub use conflict::{ConflictFileItem, ThreeWayPanes, get_conflicted_files, get_three_way_content, resolve_conflict_file, abort_merge_or_rebase, continue_merge_or_rebase};
pub use stash::{StashItem, list_stashes, save_stash, apply_stash, pop_stash, drop_stash};
pub use merge::{MergeStrategy, MergeAnalysisResult, MergeExecuteResult, analyze_merge, execute_merge};
pub use rebase::{RebaseAction, RebasePlanItem, RebaseStatus, start_interactive_rebase, continue_rebase, abort_rebase};
pub use cherrypick::{CherryPickResult, execute_cherrypick};
pub use revert::{RevertResult, execute_revert};
pub use reset::{ResetMode, ResetResult, execute_reset};
pub use checkpoint::{ConflictRisk, CheckpointItem, RollbackPreview, RollbackResult, RecoveryType, RecoveryItem, DeleteCheckpointResult, capture_pre_op, capture_manual_pin, toggle_pin_status, capture_external_cli_op, install_terminal_hooks, preview_rollback_impact, rollback_checkpoint, list_checkpoints, prune_old_checkpoints, delete_checkpoint, get_recovery_center_items};
pub use ignore::{ignore_file, unignore_file};
pub use maintenance::{run_git_gc, run_git_prune, run_git_pack_refs, run_git_repack, run_git_fsck, run_git_commit_graph};
pub use worktree::{WorktreeInfo, list_worktrees, add_worktree, remove_worktree, lock_worktree, unlock_worktree};
pub use submodule::{SubmoduleInfo, list_submodules, init_submodule, update_submodule, sync_submodule, add_submodule};
pub use hooks::{Hook, list_hooks, toggle_hook, edit_hook_script};
pub use groups::{RepoGroup, create_group, delete_group, add_to_group, remove_from_group, get_groups, bulk_fetch_group, DashboardAggregate, get_dashboard_aggregate};
pub use hosting::{HostingAccount, start_oauth_flow, list_accounts, remove_account};
pub use pull_requests::{PullRequest, list_pull_requests, create_pull_request};
pub use cicd::{CicdRun, CicdJob, CicdStep, CicdEnvironment, CicdSecret, CicdVariable, get_pipeline_runs, get_pipeline_jobs, get_pipeline_log, get_pipeline_environments, get_pipeline_secrets, get_pipeline_variables, add_pipeline_secret, add_pipeline_variable};
