pub mod error;
pub mod schema;
pub mod installation;
pub mod config;
pub mod ssh;
pub mod repository;
pub mod discovery;
pub mod dashboard;
pub mod groups;
pub mod status;
pub mod staging;
pub mod diff;
pub mod commit;
pub mod branch;
pub mod graph;
pub mod history;
pub mod remote;

pub use error::GitEngineError;
pub use installation::{GitInstallation, detect_git, set_custom_git_path, parse_git_version, check_min_version};
pub use config::{GitConfigLevel, GitConfigEntry, read_system_config, read_global_config, set_global_config, read_local_config, set_local_config, set_remote_url, set_branch_upstream, backup_global_config};
pub use ssh::{SshKey, SshConfigHost, list_ssh_keys, read_ssh_config, generate_ed25519_key, compute_fingerprint};
pub use repository::{RepositoryHandle, CloneOptions, RepoHealth, open_repository, init_repository, clone_repository, check_repository_health};
pub use discovery::scan_directories;
pub use dashboard::{RepoCard, get_dashboard_cards, pin_repository};
pub use groups::{RepoGroup, create_group, add_to_group, remove_from_group, get_groups, bulk_fetch_group};
pub use status::{FileStatus, StatusResult, DiffStats, SubmoduleSummary, get_repository_status};
pub use staging::{DiscardType, LineSelection, stage_file, unstage_file, stage_all, unstage_all, stage_patch, discard_changes};
pub use diff::{DiffLine, DiffHunk, DiffView, ImageDiff, get_file_diff, get_image_diff};
pub use commit::{CommitRequest, CommitListItem, ChangedFile, CommitDetail, HookResult, create_commit, get_commit_history, get_commit_details, execute_pre_commit_hook};
pub use branch::{BranchItem, BranchList, CheckoutStrategy, CheckoutResult, get_branches, create_branch, delete_branch, rename_branch, set_branch_upstream as branch_set_upstream, checkout_branch};
pub use graph::{GraphNode, GraphEdge, GraphView, get_commit_graph};
pub use history::{HistorySearchType, HistorySearchQuery, search_history};
pub use remote::{RemoteItem, ConnectionTestResult, FetchResult, PullStrategy, PullResult, PushResult, get_remotes, add_remote, remove_remote, edit_remote, prune_remote, test_remote_connection, fetch_remote, pull_branch, push_branch};
